---
title: "Preparing and Mining data"
author: "段海兵"
date: "2016年3月30日"
output: html_document
---
数据集来源加州大学欧文分校机器学习数据库http://archive.ics.uci.edu/ml/

Adult数据集：美国人口统计局关于影响收入因素（如年龄，工作类别，教育等）调查问卷数据，有4.8万个记录。
```{r,cache=TRUE,echo=TRUE,warning=FALSE}
#加载arules包
library(arules)
data("AdultUCI")
dim(AdultUCI)
```

```{r,cache=TRUE,echo=TRUE,warning=FALSE}
AdultUCI[1:2,]
```

fnlwgt是数据收集者创造的一个权重，education-num就是教育水平的编号

去除这两个属性
```{r,cache=TRUE,echo=TRUE,warning=FALSE}
AdultUCI[["fnlwgt"]] <- NULL
AdultUCI[["education-num"]] <- NULL
```
根据一般的经验知识将度量数据映射到顺序属性中

```{r,cache=TRUE,echo=TRUE,warning=FALSE}
#将度量属性age转换为类别，分别标记为Young,Middle-aged,Senior,Old
AdultUCI[["age"]] <- ordered(cut(AdultUCI[["age"]], c(15,25,45,65,100)),
        labels = c("Young", "Middle-aged", "Senior", "Old"))

#将度量属性hours-per-week转化为类别，分别标记为Young，Middle-aged，Senior，Old
AdultUCI[["hours-per-week"]] <- ordered(cut(AdultUCI[["hours-per-week"]], c(0,25,40,60,168)),labels = c("Part-time", "Full-time", "Over-time", "Workaholic"))

#将度量属性capital-gain转化为类别，分别标记为none，low，high
AdultUCI[["capital-gain"]] <- ordered(cut(AdultUCI[[ "capital-gain"]],      c(-Inf,0,median(AdultUCI[["capital-gain"]][AdultUCI[[ "capital-gain"]]>0]),Inf)),labels = c("None", "Low", "High"))

#将度量属性capital-loss转化为类别，分别标记为none，low，high
AdultUCI[["capital-loss"]] <- ordered(cut(AdultUCI[["capital-loss"]],          c(-Inf,0,median(AdultUCI[["capital-loss"]][AdultUCI[[ "capital-loss"]]>0]),Inf)),labels = c("none", "low", "high"))

```

```{r,cache=TRUE,echo=TRUE,warning=FALSE}
Adult <- as(AdultUCI, "transactions")
Adult
```


```{r,cache=TRUE,echo=TRUE,warning=FALSE}
 summary(Adult)
```
画出支持度大于10%的频集
```{r,cache=TRUE,echo=TRUE,warning=FALSE}
#support 支持度 cex.names=变量标签大小
itemFrequencyPlot(Adult, support = 0.1, cex.names=0.8)
```

用aprori算法找到所有支持度大于0.01，置信度大于0.6的规则
```{r,cache=TRUE,echo=TRUE,warning=FALSE}

rules <- apriori(Adult,parameter = list(support = 0.01, confidence = 0.6))
```

```{r,cache=TRUE,echo=TRUE,warning=FALSE}
rules
```

```{r,cache=TRUE,echo=TRUE,warning=FALSE}
summary(rules)
```

选取提升度大于1.2的规则
```{r,cache=TRUE,echo=TRUE,warning=FALSE}
rulesIncomeSmall <- subset(rules, subset = rhs %in% "income=small" & lift > 1.2)
rulesIncomeLarge <- subset(rules, subset = rhs %in% "income=large" & lift > 1.2)
```
查看收入低规则中，置信度最高的3个规则
```{r,cache=TRUE,echo=TRUE,warning=FALSE}
inspect(head(rulesIncomeSmall, n = 3, by = "confidence"))
```

查看收入高规则中，置信度最高的3个规则
```{r,cache=TRUE,echo=TRUE,warning=FALSE}
inspect(head(rulesIncomeLarge, n = 3, by = "confidence"))
```

将规则写入磁盘
```{r,cache=TRUE,echo=TRUE,warning=FALSE}
write(rulesIncomeSmall, file = "data.csv", sep = ",", col.names = NA)
```